### ISSUE TITLE
If you used the Raspberry pi Model A+, try it will be fine.

### ISSUE THREAD

**Issue by lualiliu** [Microsoft/uf2-linux#5]
If you want the Raspberry Pi Model A+ to support usb slave mode, please modify config.txt:

`dtoverlay=dwc2`

to
`dtoverlay=dwc2,dr_mode=peripheral`

Thanks Microsoft, thanks mmoskal.

**Comment by mmoskal** [comment]
Adafruit has pre-built images for RPi 0 and RPi 3A+ (which is the one you're referring to I think) at https://learn.adafruit.com/makecode-arcade-with-raspberry-pi-zero/firmware

**Comment by lualiliu** [comment]
> Adafruit has pre-built images for RPi 0 and RPi 3A+ (which is the one you're referring to I think) at https://learn.adafruit.com/makecode-arcade-with-raspberry-pi-zero/firmware

No, I'm just saying that raspberry pi 1 model a + can be well.

**Comment by mmoskal** [comment]
Oh, cool! Thanks!
